### ISSUE TITLE
OSError: Cannot read model

### ISSUE THREAD

**Issue by Bachstelze** [bitextor/bicleaner#33]
I want to train an Abkazhian-Russian-bicleaner with the following command inside the bicleaner repo:
`python3.7 bicleaner/bicleaner_train.py \
ru-ab-parallel.clean \
--treat_oovs --normalize_by_length \
-s ru -t ab \
-d ru-ab-probability.dic -D ab-ru-probability.dic \
-b 1000 -c ru-ab.classifier \
-g 50000 -w 50000 \
-m ru-ab.yaml \
--classifier_type random_forest \
--lm_training_file_sl lmtrain.ru-ab.ru --lm_training_file_tl lmtrain.ru-ab.ab \
--lm_file_sl model.ru-ab.ru  --lm_file_tl model.ru-ab.ab`

which results in this output:

```2020-04-26 13:28:37,419 - INFO - Training LM-based fluency filter
2020-04-26 13:28:37,420 - INFO - SL & TL LM training corpora have been obtained from tab-separated input file (the same ones used for training the Random Forest classifier), after randomly removing 2000 sentences
2020-04-26 13:28:37,420 - INFO - SL & TL LM dev clean corpora have been randomly selected from input input file (the same used for training the Random Forest classifier): 2000 sentences
2020-04-26 13:28:41,859 - INFO - SL LM dev noisy corpus: /tmp/tmphputkitp
2020-04-26 13:28:44,090 - INFO - TL LM dev noisy corpus: /tmp/tmpb39wtfty
/bin/sh: 1: lmplz: not found
/bin/sh: 1: build_binary: not found
Loading the LM will be faster if you build a binary file.
Reading /tmp/tmppj1xqm2l
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
Traceback (most recent call last):
  File "kenlm.pyx", line 128, in kenlm.Model.__init__
RuntimeError: End of file Byte: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kalle/workspaces/bicleaner/bicleaner/lm.py", line 223, in train
    self.sl_filter.train_lm(lm_train_sl)
  File "/home/kalle/workspaces/bicleaner/bicleaner/lm.py", line 147, in train_lm
    self.lm=kenlm.LanguageModel(self.lm_path)
  File "kenlm.pyx", line 131, in kenlm.Model.__init__
OSError: Cannot read model '/tmp/tmppj1xqm2l' (End of file Byte: 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bicleaner/bicleaner_train.py", line 456, in <module>
    main(args)
  File "bicleaner/bicleaner_train.py", line 451, in main
    perform_training(args)
  File "bicleaner/bicleaner_train.py", line 346, in perform_training
    stats=train_fluency_filter(args)
  File "/home/kalle/workspaces/bicleaner/bicleaner/training.py", line 118, in train_fluency_filter
    stats=ff.train(lm_train_path_sl, lm_train_path_tl,lm_dev_clean_sl,lm_dev_clean_tl, args.noisy_examples_file_sl,args.noisy_examples_file_tl, args.lm_file_sl, args.lm_file_tl)
  File "/home/kalle/workspaces/bicleaner/bicleaner/lm.py", line 232, in train
    self.tl_filter.cleanup()
  File "/home/kalle/workspaces/bicleaner/bicleaner/lm.py", line 157, in cleanup
    os.remove(self.lm_path)
AttributeError: 'LMFluencyFilter' object has no attribute 'lm_path'
```

Any suggestions why the End of file Byte is null and wrong?

**Comment by mbanon** [comment]
Hi @Bachstelze ,
I can see this in your output:
```
/bin/sh: 1: lmplz: not found
/bin/sh: 1: build_binary: not found
```
suggesting that the problem is your installation of KenLM.
Could you please follow this steps to install it? https://github.com/bitextor/bicleaner/wiki/How-to-train-your-Bicleaner#kenlm

I hope this solves the error. Please let me know if you are still experiencing issues :)

-Marta

**Comment by Bachstelze** [comment]
There are several installations of KenLM on my system: with cmake  and pip for both python3.6, python3.7 versions. I don't know which is used or doesn't function. Hopefully a reinstallation of my system will clean the mess.
Thanks for your help so far.

**Comment by Bachstelze** [comment]
The different versions of python confuse me. So the bicleaner is trained with python3.7, but KenLM is installed for python3.6?

**Comment by ZJaume** [comment]
Hi @batchelze,

The tutorial was probably written before the update to python 3.7, so that command has to be `python3.7 -m pip install .` if you set up your environment with Python 3.7.  Furthermore, I advise you to create a virtual environment on your working directory, source it, clone KenLM, install it into the environment and run cmake pointing to that virtualenv. All of that using Python 3.7.

```
python3.7 -m venv venv
source venv/bin/activate
python3.7 -m pip install bicleaner
git clone https://github.com/kpu/kenlm cd kenlm
python3.7 -m pip install . --install-option="--max_order 7"
cd build
cmake .. -DKENLM_MAX_ORDER=7 -DCMAKE_INSTALL_PREFIX:PATH=/your/python/venv/path/here/
make -j all install 
```

**Comment by mbanon** [comment]
> The tutorial was probably written before the update to python 3.7, so that command has to be `python3.7 -m pip install .` if you set up your environment with Python 3.7. 


That's right, I've just updated the tutorial.

**Comment by Bachstelze** [comment]
Thank you a lot! Now it is working.
Have a nice Labour Day!
