### ISSUE TITLE
Training failed.

### ISSUE THREAD

**Issue by cidrugHug8** [bitextor/bicleaner#42]
While training classifier I got some error described below:
```
2020-07-09 05:15:27,568 - INFO - Starting process
2020-07-09 05:15:27,568 - INFO - Running 31 workers at 1000 rows per block
2020-07-09 05:15:53,413 - INFO - Training LM-based fluency filter
2020-07-09 05:15:53,414 - INFO - SL & TL LM training corpora have been obtained from tab-separated input file (the same ones used for training the Random Forest classifier), after randomly removing 2000 sentences
2020-07-09 05:15:53,414 - INFO - SL & TL LM dev clean corpora have been randomly selected from input input file (the same used for training the Random Forest classifier): 2000 sentences
2020-07-09 05:15:53,414 - INFO - SL LM dev noisy corpus: ./sample/2020-06-25/noisy.en-ja.en
2020-07-09 05:15:53,414 - INFO - TL LM dev noisy corpus: ./sample/2020-06-25/noisy.en-ja.ja
...
2020-07-09 08:05:17,803 - INFO - killing process 10374
2020-07-09 08:05:17,805 - INFO - killing process 10388
2020-07-09 08:11:16,444 - INFO - Start training
Traceback (most recent call last):
  File "./bicleaner/bicleaner/bicleaner_train.py", line 421, in <module>
    main(args)
  File "./bicleaner/bicleaner/bicleaner_train.py", line 417, in main
    perform_training(args)
  File "./bicleaner/bicleaner/bicleaner_train.py", line 397, in perform_training
    hgood, hwrong = train_classifier(features_train, features_test, args.classifier_type, args.classifier)
  File "./bicleaner/bicleaner/bicleaner_train.py", line 166, in train_classifier
    good.append(pred[1])
IndexError: index 1 is out of bounds for axis 0 with size 1
```
Training parameters are here:
```
  python3 ./bicleaner/bicleaner/bicleaner_train.py \
    "${SEED}.sp.en-ja.bifixed" \
    --treat_oovs --normalize_by_length \
    --qmax_limit 40 \
    -s en -t ja \
    -d "${DIR}/dict.en.gz" -D "${DIR}/dict.ja.gz" \
    -b 1000 \
    -g 50000 -w 50000 \
    -c "${DIR}/en-ja.classifier" \
    -m "${DIR}/en-ja.yaml" \
    --classifier_type random_forest \
    --wrong_examples_file "${DIR}/wrong.en-ja" \
    --noisy_examples_file_sl "${DIR}/noisy.en-ja.en" \
    --noisy_examples_file_tl "${DIR}/noisy.en-ja.ja" \
    --lm_training_file_sl "${DIR}/lmtrain.en-ja.en" \
    --lm_training_file_tl "${DIR}/lmtrain.en-ja.ja" \
    --lm_file_sl "${DIR}/model.en-ja.en" \
    --lm_file_tl "${DIR}/model.en-ja.ja"
```
Could you give me some advice?

Best regards

**Comment by mbanon** [comment]
Hi @cidrugHug8 ,
thanks for your feedback.

We are investigating the issue, I assume you are using the master branch, right?
Could you please provide a line count of the following files?

* `${SEED}.sp.en-ja.bifixed`
* `${DIR}/wrong.en-ja`


BTW, I noticed you are using japanese as your target language. Bicleaner currently uses MosesTokenizer. You may want to use a target tokenizer of your choice by using the  `-T` flag (https://github.com/bitextor/bicleaner/#parameters-1) (it should be the same tokenizer used to build probabilistic dictionaries)

Thanks,
-Marta

**Comment by cidrugHug8** [comment]
Hi Marta,
thanks for your reply.

Yes, I used the master branch.
```
  10062199 ${SEED}.sp.en-ja.bifixed
     54598 ${DIR}/wrong.en-ja
```
Oops, I found out why it failed. ${DIR}/wrong.en-ja was monolingual.
I rebuilt the corpus and it looks to work. 

So my new question is, I tokenized my corpus using sentencepiece, how can I give the -S and -T options an argument in addition to the program full path?

Best regards

**Comment by mbanon** [comment]
Hi,
I am glad you found the error and it's working now :)

I am not 100% sure that if in the master version would work something like `-T "/path/to/the/tokenizer -with -your -arguments"` (we've been improving this in [version 0.14](https://github.com/bitextor/bicleaner/tree/bicleaner-0.14) that is coming soon). If not, wrapping your command and arguments in a dummy script that just read standard input, runs the external tokenizer with your arguments, and writes standard output should do the trick.

**Comment by cidrugHug8** [comment]
By following your advice, I was able to specify the full path and argument of the tokenizer with the -S option and -T. I'm waiting for the results of the execution now.

Thank you very much!
