### ISSUE TITLE
Training failed with the -S and -T options.

### ISSUE THREAD

**Issue by cidrugHug8** [bitextor/bicleaner#43]
While training classifier I got some error described below:
```
2020-07-15 10:26:13,197 - INFO - spawned process 10999
Process Process-3:
Traceback (most recent call last):
  File "/home/hiroshi/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/hiroshi/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hiroshi/anaconda3/lib/python3.7/site-packages/bicleaner/bicleaner_train.py", line 270, in worker_process
    features = feature_extract(srcsen, trgsen, source_tokeniser, target_tokeniser, args)
  File "/home/hiroshi/anaconda3/lib/python3.7/site-packages/bicleaner/features.py", line 350, in feature_extract
    tokenize_l.writeline(srcsen.rstrip('\n'))
  File "/home/hiroshi/anaconda3/lib/python3.7/site-packages/toolwrapper.py", line 134, in writeline
    self.stdin.write(line + '\n')
BrokenPipeError: [Errno 32] Broken pipe
2020-07-15 10:26:13,199 - INFO - killing process 10913
Exception ignored in: <function ToolWrapper.__del__ at 0x7fb4feebdb90>
Traceback (most recent call last):
  File "/home/hiroshi/anaconda3/lib/python3.7/site-packages/toolwrapper.py", line 55, in __del__
    self.close()
  File "/home/hiroshi/anaconda3/lib/python3.7/site-packages/toolwrapper.py", line 126, in close
    getattr(self, attr).close()
BrokenPipeError: [Errno 32] Broken pipe
...
2020-07-15 10:26:13,340 - INFO - Start mapping
2020-07-15 10:26:13,454 - INFO - End mapping
2020-07-15 10:26:13,467 - INFO - Start training
Traceback (most recent call last):
  File "/home/hiroshi/anaconda3/bin/bicleaner-train", line 11, in <module>
    main(sys.argv[1:])
  File "/home/hiroshi/anaconda3/bin/bicleaner-train", line 8, in main
    train.main(args)
  File "/home/hiroshi/anaconda3/lib/python3.7/site-packages/bicleaner/bicleaner_train.py", line 451, in main
    perform_training(args)
  File "/home/hiroshi/anaconda3/lib/python3.7/site-packages/bicleaner/bicleaner_train.py", line 429, in perform_training
    hgood, hwrong, feat_importances = train_classifier(features_train, features_test, args.classifier_type, args.classifier)
  File "/home/hiroshi/anaconda3/lib/python3.7/site-packages/bicleaner/bicleaner_train.py", line 163, in train_classifier
    clf.fit(dataset['data'], dataset['target'])
  File "/home/hiroshi/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/_forest.py", line 295, in fit
    X = check_array(X, accept_sparse="csc", dtype=DTYPE)
  File "/home/hiroshi/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 556, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
```
Training parameters are here:
```
  bicleaner-train \
    "${SEED}.en-ja.bifixed" \
    -S '/home/hiroshi/.local/bin/yttm encode --stream --model "/home/hiroshi/ssd/filtering-corpus/'${TOK}.bpe'" --output_type subword --dropout_prob 0.1' \
    -T '/home/hiroshi/.local/bin/yttm encode --stream --model "/home/hiroshi/ssd/filtering-corpus/'${TOK}.bpe'" --output_type subword --dropout_prob 0.1' \
    --treat_oovs --normalize_by_length \
    --qmax_limit 40 \
    -s en -t ja \
    -d "${DIR}/dict.en.gz" -D "${DIR}/dict.ja.gz" \
    -b 1000 \
    -g 50000 -w 50000 \
    -c "${DIR}/en-ja.classifier" \
    -m "${DIR}/en-ja.yaml" \
    --classifier_type random_forest \
    --noisy_examples_file_sl "${DIR}/noisy.en-ja.en" \
    --noisy_examples_file_tl "${DIR}/noisy.en-ja.ja" \
    --lm_training_file_sl "${DIR}/lmtrain.en-ja.en" \
    --lm_training_file_tl "${DIR}/lmtrain.en-ja.ja" \
    --lm_file_sl "${DIR}/model.en-ja.en" \
    --lm_file_tl "${DIR}/model.en-ja.ja"
```
Could you look at that and give me some advice?

Best regards

**Comment by cidrugHug8** [comment]
wait, i mistaken again. i'm checking.

**Comment by cidrugHug8** [comment]
resolved.
