### ISSUE TITLE
OSError: Cannot read model; lmplz: not found

### ISSUE THREAD

**Issue by xpertasks** [bitextor/bicleaner#48]
Hi,

I am getting the following error while training with bicleaner_train.py

```
2020-10-07 10:25:29,574 - INFO - Training LM-based fluency filter.
2020-10-07 10:25:29,574 - INFO - SL & TL LM training corpora have been obtained from tab-separated input file (the same ones used for training the classifier), after random$
y removing 2000 sentences.
2020-10-07 10:25:29,574 - INFO - SL & TL LM dev clean corpora have been randomly selected from input input file (the same used for training the classifier): 2000 sentences.
2020-10-07 10:36:38,709 - INFO - SL LM dev noisy corpus: /tmp/tmpl4_8ntv3
2020-10-07 10:40:38,215 - INFO - TL LM dev noisy corpus: /tmp/tmpjo125lyi
Loading the LM will be faster if you build a binary file.
Reading /tmp/tmpweo8xvqs
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
Traceback (most recent call last):
  File "kenlm.pyx", line 139, in kenlm.Model.__init__
RuntimeError: End of file Byte: 0
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/raid0/sukanta/tools/bicleaner/bicleaner/lm.py", line 232, in train
    self.sl_filter.train_lm(lm_train_sl)
  File "/raid0/sukanta/tools/bicleaner/bicleaner/lm.py", line 154, in train_lm
    self.lm=kenlm.LanguageModel(self.lm_path)
  File "kenlm.pyx", line 142, in kenlm.Model.__init__
OSError: Cannot read model '/tmp/tmpweo8xvqs' (End of file Byte: 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/fs/vor0/sukanta/tools/bicleaner/bicleaner/bicleaner_train.py", line 523, in <module>
    main(args)
  File "/fs/vor0/sukanta/tools/bicleaner/bicleaner/bicleaner_train.py", line 519, in main
    perform_training(args)
  File "/fs/vor0/sukanta/tools/bicleaner/bicleaner/bicleaner_train.py", line 402, in perform_training
    stats=train_fluency_filter(args)
  File "/raid0/sukanta/tools/bicleaner/bicleaner/training.py", line 116, in train_fluency_filter
    stats=ff.train(lm_train_path_sl, lm_train_path_tl,lm_dev_clean_sl,lm_dev_clean_tl, args.noisy_examples_file_sl,args.noisy_examples_file_tl, args.lm_file_sl, args.lm_file
_tl)
  File "/raid0/sukanta/tools/bicleaner/bicleaner/lm.py", line 241, in train
    self.tl_filter.cleanup()
  File "/raid0/sukanta/tools/bicleaner/bicleaner/lm.py", line 164, in cleanup
    os.remove(self.lm_path)
AttributeError: 'LMFluencyFilter' object has no attribute 'lm_path'
```
There is already one similar issue: https://github.com/bitextor/bicleaner/issues/33. But it did not help me. Removing `stderr=PIPE, stdout=PIPE` and adding `check=True` in https://github.com/bitextor/bicleaner/blob/master/bicleaner/lm.py#L89 helped me find the issue, and I resolved it by adding the absolute paths to `lmplz` and `build_binary`. I think adding one more option for kenlm path, if I did not miss this option, to bicleaner_train.py and then adding absolute path in lm.py#L89 lm.py#L92 will handle it better.

**Comment by jelmervdl** [comment]
It would be helpful if `_estimate_kenlm` has some form of checking going on, it would make debugging this and other issues with kenlm a bit easier.

Suggested: Either with `check=True` in the `subprocess.run()` calls (but then mind that you don't get to see the error message as the logging lines are never reached) or by checking the `returncode` of the return value.

**Comment by ZJaume** [comment]
I'm trying to reproduce this bug and try to check status. I've rebuild KenLM without the `CMAKE_PREFIX` option and print to logging the stderr if return code from `lmplz` is different than 0:
```python
output = subprocess.run("lmplz "+params+" < "+corpus+" > "+lm_file+".arpa", shell=True, stderr=PIPE, stdout=PIPE)
if output.returncode != 0:
     logging.error(output.stderr.decode())
     logging.error(output.stdout.decode())
     sys.exit(1)
else:
      logging.debug(output.stderr.decode())
      logging.debug(output.stdout.decode())
```
but the output is not very informative, it only adds:
```
/work/bicleaner-testing/kenlm/util/scoped.cc:20 in void* util::{anonymous}::InspectAddr(void*, std::size_t, const char*) threw MallocException because `!addr && requested'.
Cannot allocate memory for 185237012448 bytes in malloc
Aborted (core dumped)
```

Maybe an error message that says "check your kenlm install prefix installation" could be added if the return code is error, but I don't have more ideas.

**Comment by jelmervdl** [comment]
I don't understand. That error seems to tell you that it can still find lmplz (apparently it's still in your PATH) but it runs out of memory. I would say that's already more informative than an unrelated AttributeError.
