### ISSUE TITLE
Tests don't pass

### ISSUE THREAD

**Issue by onadegibert** [bitextor/bicleaner#76]
Hi there,

I have followed the conda installation instructions and there seems to be an issue, since tests don't pass.

```
conda create --name run-bicleaner python=3.8
conda activate run-bicleaner
conda install -c conda-forge -c bitextor bicleaner
python -m pytest -s tests/bicleaner_test.py

============================================================== test session starts ==============================================================
platform linux -- Python 3.8.16, pytest-7.1.1, pluggy-1.0.0
rootdir: /home/local/degibert/Documents/Tools/Bicleaner/bicleaner
collected 4 items                                                                                                                               

tests/bicleaner_test.py Running test setup...

Running test body...
/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/sklearn/base.py:313: UserWarning: Trying to unpickle estimator ExtraTreeClassifier from version 1.1.3 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
2023-02-14 10:04:28,811 - ERROR - Error loading metadata
Traceback (most recent call last):
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/bicleaner/classify.py", line 102, in load_metadata
    args.clf=joblib.load( os.path.join( yamlpath , metadata_yaml["classifier"]))
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/pickle.py", line 1212, in load
    dispatch[key[0]](self)
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/bicleaner/classify.py", line 104, in load_metadata
    args.clf=joblib.load(metadata_yaml["classifier"])
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 579, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'en-de.classifier'
Checking test results...
FRunning test body...
/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/sklearn/base.py:313: UserWarning: Trying to unpickle estimator ExtraTreeClassifier from version 1.1.3 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
2023-02-14 10:04:30,131 - ERROR - Error loading metadata
Traceback (most recent call last):
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/bicleaner/classify.py", line 102, in load_metadata
    args.clf=joblib.load( os.path.join( yamlpath , metadata_yaml["classifier"]))
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/pickle.py", line 1212, in load
    dispatch[key[0]](self)
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/bicleaner/classify.py", line 104, in load_metadata
    args.clf=joblib.load(metadata_yaml["classifier"])
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 579, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'en-de.classifier'
Checking test results...
FRunning test body...
/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/sklearn/base.py:313: UserWarning: Trying to unpickle estimator ExtraTreeClassifier from version 1.1.3 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
2023-02-14 10:04:31,410 - ERROR - Error loading metadata
Traceback (most recent call last):
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/bicleaner/classify.py", line 102, in load_metadata
    args.clf=joblib.load( os.path.join( yamlpath , metadata_yaml["classifier"]))
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/pickle.py", line 1212, in load
    dispatch[key[0]](self)
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/bicleaner/classify.py", line 104, in load_metadata
    args.clf=joblib.load(metadata_yaml["classifier"])
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 579, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'en-de.classifier'
Checking test results...
FRunning test body...
/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/sklearn/base.py:313: UserWarning: Trying to unpickle estimator ExtraTreeClassifier from version 1.1.3 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
2023-02-14 10:04:32,714 - ERROR - Error loading metadata
Traceback (most recent call last):
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/bicleaner/classify.py", line 102, in load_metadata
    args.clf=joblib.load( os.path.join( yamlpath , metadata_yaml["classifier"]))
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/pickle.py", line 1212, in load
    dispatch[key[0]](self)
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/bicleaner/classify.py", line 104, in load_metadata
    args.clf=joblib.load(metadata_yaml["classifier"])
  File "/home/degibert/.conda/envs/run-bicleaner/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 579, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'en-de.classifier'
Checking test results...
FRunning test teardown...


=================================================================== FAILURES ====================================================================
_______________________________________________________________ test_full_process _______________________________________________________________

    def test_full_process():
        expected = [0, 0, 0, 0, 0, 0.5, 0, 0.1, 0.3, 0]
        results = bicleaner_test("bicleaner-classify","en-de.yaml")
        print("Checking test results...")
        for  i in range(len(expected)):
>               assert(results[i] == expected[i])
E     IndexError: list index out of range

tests/bicleaner_test.py:64: IndexError
____________________________________________________________ test_full_process_nolm _____________________________________________________________

    def test_full_process_nolm():
        expected = [0, 0, 0, 0, 0, 0.5, 0, 0.1, 0.3, 0]
        results = bicleaner_test("bicleaner-classify","en-de.nolm.yaml")
        print("Checking test results...")
        for  i in range(len(expected)):
>               assert(results[i] == expected[i])
E     IndexError: list index out of range

tests/bicleaner_test.py:71: IndexError
_______________________________________________________________ test_lite_process _______________________________________________________________

    def test_lite_process():
            expected = [0, 0, 0, 0, 0, 0.5, 0, 0.1, 0.3, 0]
            results = bicleaner_test("bicleaner-classify-lite","en-de.yaml")
            print("Checking test results...")
            for  i in range(len(expected)):
>                   assert(results[i] == expected[i])
E                   IndexError: list index out of range

tests/bicleaner_test.py:78: IndexError
____________________________________________________________ test_lite_process_nolm _____________________________________________________________

    def test_lite_process_nolm():
            expected = [0, 0, 0, 0, 0, 0.5, 0, 0.1, 0.3, 0]
            results = bicleaner_test("bicleaner-classify-lite","en-de.nolm.yaml")
            print("Checking test results...")
            for  i in range(len(expected)):
>                   assert(results[i] == expected[i])
E                   IndexError: list index out of range

tests/bicleaner_test.py:86: IndexError
============================================================ short test summary info ============================================================
FAILED tests/bicleaner_test.py::test_full_process - IndexError: list index out of range
FAILED tests/bicleaner_test.py::test_full_process_nolm - IndexError: list index out of range
FAILED tests/bicleaner_test.py::test_lite_process - IndexError: list index out of range
FAILED tests/bicleaner_test.py::test_lite_process_nolm - IndexError: list index out of range
============================================================== 4 failed in 58.94s ===============================================================
```

**Comment by ZJaume** [comment]
Conda installation is maintained by bitextor people and right now it is outdated. Tests are failing probably because the test is downloading latest model and that model is trained with sklearn 1.0 which is incompatible with 0.22 (used in the 0.15.2 bicleaner version published at conda).

If you want to use a conda environment and don't need bitextor, you can just install it with pip install after the activation of the environment. Instead of doing `conda install -c conda-forge -c bitextor bicleaner`. With this, they should pass. At least for me, are passing.

Another thing you can do is change the model used for the test, to the one that bicleaner 0.15 was made for.
this line 
https://github.com/bitextor/bicleaner/blob/77ac0057c11807d16c0a07c7b96dc4ed9d33cf31/tests/bicleaner_test.py#L14
by this link https://github.com/bitextor/bicleaner-data/releases/download/v1.5/en-de.tar.gz. But in this case you'll be running an old bicleaner version.

**Comment by onadegibert** [comment]
Worked! Thanks :)
